#!/bin/bash

if [ -t 1 ]; then 
  c_cyan=`tput setaf 6`
  c_red=`tput setaf 1`
  c_green=`tput setaf 2`
  c_orange=`tput setaf 214`
  c_bgr=`tput setaf 236`
  p_green=`tput setaf 10`
  p_pink=`tput setaf 13`
  p_blue=`tput setaf 4`
  p_reset=`tput sgr0`
fi
